# Generated by Django 4.2.20 on 2025-03-26 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('course_number', models.CharField(max_length=10)),
                ('meeting_day', models.CharField(max_length=10)),
                ('room_capacity', models.IntegerField()),
                ('predicted_enrollment', models.IntegerField()),
                ('seats_available', models.IntegerField()),
                ('building', models.CharField(max_length=50)),
                ('room', models.CharField(max_length=10)),
                ('begin_time', models.CharField(max_length=10)),
                ('end_time', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
